Class {
	#name : #ECUTestObject,
	#superclass : #Object,
	#instVars : [
		'a',
		'b',
		'c'
	],
	#category : #'Seeker-Tests-ECU'
}

{ #category : #accessing }
ECUTestObject >> a [

	^ a
]

{ #category : #accessing }
ECUTestObject >> a: anObject [

	a := anObject
]

{ #category : #accessing }
ECUTestObject >> b [

	^ b
]

{ #category : #accessing }
ECUTestObject >> b: anObject [

	b := anObject
]

{ #category : #accessing }
ECUTestObject >> c [

	^ c
]

{ #category : #accessing }
ECUTestObject >> c: anObject [

	c := anObject
]
