Class {
	#name : #SkExperimentTasks,
	#superclass : #TestCase,
	#category : #'Seeker-BugCollection-Tests'
}

{ #category : #tests }
SkExperimentTasks >> test_T01_MetacelloVersionNumberTestCase_testApproxVersion02 [

	(MetacelloVersionNumberTestCase >> #testApproxVersion02) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T02_FuzzyMatcherTest_testAllMatchingIn [

	(FuzzyMatcherTest >> #testAllMatchingIn) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T03_RSNormalizerTest_testBasic [

	(RSNormalizerTest >> #testBasic) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T04_NSPowScaleTest_testSqrt [

	(NSPowScaleTest >> #testSqrt) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T05_DoubleLinkedListTes_testDo [

	(DoubleLinkedListTest >> #testDo) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T06_MethodMapTest_testBlockAndContextSourceNode [

	(MethodMapTest>>#testBlockAndContextSourceNode) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T07_MicToPillarBasicTest_testHeader [

	(MicToPillarBasicTest>>#testHeader) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T08_MicToPillarBasicTest_testCodeBlock [

	(MicToPillarBasicTest >> #testCodeBlock) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T09_HiRulerBuilderTest_testCycle [

	(HiRulerBuilderTest>>#testCycle) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T10_GLineTest_testAsGLine [

	(GLineTest>>#testAsGLine) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T11_NestedDictionaryTest_testAtAtPut [

	(NestedDictionaryTest >> #testAtAtPut) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T12_GLineTest_testAngleWith [

	(GLineTest >> #testAngleWith) browse
]
