Class {
	#name : #SkExperimentTasks,
	#superclass : #TestCase,
	#category : #'Seeker-BugCollection-Tests'
}

{ #category : #tests }
SkExperimentTasks >> test_T01_MetacelloVersionNumberTestCase_testApproxVersion02 [

	(MetacelloVersionNumberTestCase >> #testApproxVersion02) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T02_FuzzyMatcherTest_testAllMatchingIn [

	(FuzzyMatcherTest >> #testAllMatchingIn) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T03_RSNormalizerTest_testBasic [

	(RSNormalizerTest >> #testBasic) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T04_NSPowScaleTest_testSqrt [

	(NSPowScaleTest >> #testSqrt) browse
]

{ #category : #tests }
SkExperimentTasks >> test_T05_DoubleLinkedListTes_testDo [

	(DoubleLinkedListTest >> #testDo) browse
]
